NFL/Equipos/urls.py
from django.urls import path
from Equipos import views

app_name = "equipos"

urlpatterns = [
    path('list/', views.List.as_view(), name="list"),
    path("create/", views.Create.as_view(), name="create"),
    path("delete/", views.Delete.as_view(), name="delete"),
    path("detail/", views.Detail.as_view(), name="detail"),
    path("update/", views.Update.as_view(), name="update"),
]

NFL/NFL/urls.py
from django.contrib import admin
from django.urls import path, include

from Equipos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ciudades/', include('Ciudades.urls')),
    path('estadios/', include('Estadios.urls')),
    path('equipos/', include('Equipos.urls')),
]

NFL/Equipos/models.py
from django.db import models
from Ciudades.models import Ciudades
from Estadios.models import Estadio

# Create your models here.
class Equipos(models.Model):
    nombre = models.CharField(max_length=255)
    ciudad = models.ForeignKey(Ciudades, on_delete = models.CASCADE)
    estadio = models.ForeignKey(Estadio, on_delete = models.CASCADE)

    def __str__(self):
        return self.nombre

NFL/Equipos/forms.py
from django import forms
from Equipos.models import Equipos

class EquiposForm(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={
                    "type": "text",
                        "placeholder": "Ingrese el nombre"
                }
            ),
            "ciudad": forms.Select(attrs={
                    "type": "Select"
                }
            ),
            "estadio": forms.Select(attrs={
                "type": "Select"
                }
            )
        }

class UpdateEquiposForm(forms.ModelForm):
    class Meta:
        model = Equipos
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={
                    "type": "text",
                        "placeholder": "Ingrese el nombre"
                }
            ),
            "ciudad": forms.Select(attrs={
                    "type": "Select"
                }
            ),
            "estadio": forms.Select(attrs={
                "type": "Select"
                }
            )
        }

NFL/Equipos/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Equipos
from .forms import EquiposForm, UpdateEquiposForm

# Create your views here.
class Create(generic.CreateView):
    template_name = "equipos/create.html"
    model = Equipos
    form_class = EquiposForm
    success_url = reverse_lazy('equipos:list')

class Detail(generic.ListView):
    template_name = "equipos/list.html"
    model = Equipos #queryset = GrantGoal.objects.filter(status=True)

class List(generic.View):
    template_name = "equipos/detail.html"
    context = {}

    def get(self, request, *args, **kwargs):
        equipos = Equipos.objects.all()
        self.context = {
            "equipos": equipos
        }
        return render(request, self.template_name, self.context)

class Update(generic.CreateView):
    template_name = "equipos/update.html"
    model = Equipos
    form_class = UpdateEquiposForm
    success_url = reverse_lazy('equipos:list')


class Delete(generic.DeleteView):
    template_name = "equipos/delete.html"
    model = Equipos
    success_url = reverse_lazy('equipos:list')

NFL/templates/equipos/create.html
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Agregar equipo</button>
        <a href="{% url 'equipos:list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>

NFL/templates/equipos/delete.html
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Deseas eliminar: {{ object }}?
        <button type="submit" class="btn btn-primary">Eliminar equipo</button>
        <a href="{% url 'equipos:list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>

NFL/templates/equipos/detail.html
<h1>Nombre equipo: {{ object.nombre }}</h1>
<h1>Ciuada del equipo: {{ object.ciudad }}</h1>
<h1>Estadio del equipo: {{ object.estadio }}</h1>

NFL/templates/equipos/list.html
<a href="{% url 'equipos:create' %}">Agregar ciudad</a>
<br>
<table>
    <thead>
      <th>ID</th>
      <th>NOMBRE</th>
      <th>CIUDAD</th>
      <th>ESTADIO</th>
      <th></th>
      <th>ACTIONS</th>
      <th></th>
    </thead>
    <tbody>
      {% for x in equipos %}
        <tr>
          <td>{{ x.id }}</td>
          <td>{{ x.name }}</td>
          <td>{{ x.ciudad }}</td>
          <td>{{ x.estadio }}</td>
          <td><a href="{% url 'cities:city_detail' city.id %}" class="btn btn-info">Details</a></td>
          <td><a href="{% url 'cities:city_update' city.id %}" class="btn btn-warning">Update</a></td>
          <td><a href="{% url 'cities:city_delete' city.id %}" class="btn btn-primary">Delete</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

NFL/templates/equipos/update.html
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Actualizar equipo</button>
        <a href="{% url 'equipos:list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>