NFL/Ciudades/urls.py
from django.urls import path
from Ciudades import views

app_name = "ciudades"

urlpatterns = [
    path('list/', views.List.as_view(), name="list"),
    path("create/", views.Create.as_view(), name="create"),
    path("delete/", views.Delete.as_view(), name="delete"),
    path("detail/", views.Detail.as_view(), name="detail"),
    path("update/", views.Update.as_view(), name="update"),
]

NFL/NFL/urls.py
from django.contrib import admin
from django.urls import path, include

from Equipos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ciudades/', include('Ciudades.urls')),
    path('estadios/', include('Estadios.urls')),
    path('equipos/', include('Equipos.urls')),
]

NFL/Ciudades/models.py
from django.db import models

# Create your models here.
class Ciudades(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__():
        return self.nombre

NFL/Ciudades/forms.py
from django import forms
from Ciudades.models import Ciudades

class CiudadesForm(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={
                "type": "text",
                "placeholder": "Ingrese el nombre"
            })
        }

class UpdateCiudadesForm(forms.ModelForm):
    class Meta:
        model = Ciudades
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={
                "type": "text",
                "placeholder": "Ingrese el nombre"
            })
        }

NFL/Ciudades/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Ciudades
from .forms import CiudadesForm, UpdateCiudadesForm

# Create your views here.
class Create(generic.CreateView):
    template_name = "ciudades/create.html"
    model = Ciudades
    form_class = CiudadesForm
    success_url = reverse_lazy('ciudades:list')

class Detail(generic.ListView):
    template_name = "ciudades/list.html"
    model = Ciudades #queryset = GrantGoal.objects.filter(status=True)

class List(generic.View):
    template_name = "ciudades/detail.html"
    context = {}

    def get(self, request, *args, **kwargs):
        ciudades = Ciudades.objects.all()
        self.context = {
            "ciudades": ciudades
        }
        return render(request, self.template_name, self.context)

class Update(generic.CreateView):
    template_name = "ciudades/update.html"
    model = Ciudades
    form_class = UpdateCiudadesForm
    success_url = reverse_lazy('ciudades:list')


class Delete(generic.DeleteView):
    template_name = "ciudades/delete.html"
    model = Ciudades
    success_url = reverse_lazy('ciudades:list')

NFL/templates/ciudades/create.html
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Agregar ciudad</button>
        <a href="{% url 'ciudades:list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>

NFL/templates/ciudades/delete.html
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Deseas eliminar: {{ object }}?
        <button type="submit" class="btn btn-primary">Eliminar ciudad</button>
        <a href="{% url 'ciudad:list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>

NFL/templates/ciudades/detail.html
<h1>Nombre de la ciuad: {{ object.nombre }}</h1>

NFL/templates/ciudades/list.html
<a href="{% url 'ciudades:create' %}">Agregar ciudad</a>
<br>
<table>
    <thead>
      <th>ID</th>
      <th>NOMBRE</th>
      <th></th>
      <th>ACTIONS</th>
      <th></th>
    </thead>
    <tbody>
      {% for x in ciudades %}
        <tr>
          <td>{{ x.id }}</td>
          <td>{{ x.name }}</td>
          <td><a href="{% url 'cities:city_detail' city.id %}" class="btn btn-info">Details</a></td>
          <td><a href="{% url 'cities:city_update' city.id %}" class="btn btn-warning">Update</a></td>
          <td><a href="{% url 'cities:city_delete' city.id %}" class="btn btn-primary">Delete</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

NFL/templates/ciudades/update.html
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Actualizar ciudad</button>
        <a href="{% url 'ciudades:list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>