NFL/Estadios/urls.py
from django.urls import path
from Estadios import views

app_name = "estadios"

urlpatterns = [
    path('list/', views.List.as_view(), name="list"),
    path("create/", views.Create.as_view(), name="create"),
    path("delete/", views.Delete.as_view(), name="delete"),
    path("detail/", views.Detail.as_view(), name="detail"),
    path("update/", views.Update.as_view(), name="update"),
]

NFL/NFL/urls.py
from django.contrib import admin
from django.urls import path, include

from Equipos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ciudades/', include('Ciudades.urls')),
    path('estadios/', include('Estadios.urls')),
    path('equipos/', include('Equipos.urls')),
]

NFL/Estadios/models.py
from django.db import models
from Ciudades.models import Ciudades

# Create your models here.
class Estadio(models.Model):
    nombre = models.CharField(max_length=255)
    ciudad = models.ForeignKey(Ciudades, on_delete = models.CASCADE)

    def __str__(self):
        return self.nombre

NFL/Estadios/forms.py
from django import forms
from Estadios.models import Estadio

class EstadiosForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={
                    "type": "text",
                        "placeholder": "Ingrese el nombre"
                }
            ),
            "ciudad": forms.Select(attrs={
                    "type": "Select"
                }
            )
        }


class UpdateEstadiosForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={
                    "type": "text",
                        "placeholder": "Ingrese el nombre"
                }
            ),
            "ciudad": forms.Select(attrs={
                    "type": "Select"
                }
            )
        }

NFL/Estadios/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Estadio
from .forms import EstadiosForm, UpdateEstadiosForm

# Create your views here.
class Create(generic.CreateView):
    template_name = "estadios/create.html"
    model = Estadio
    form_class = EstadiosForm
    success_url = reverse_lazy('estadios:list')

class Detail(generic.ListView):
    template_name = "estadios/list.html"
    model = Estadio

class List(generic.View):
    template_name = "estadios/detail.html"
    context = {}

    def get(self, request, *args, **kwargs):
        estadios = Estadio.objects.all()
        self.context = {
            "estadios": estadios
        }
        return render(request, self.template_name, self.context)

class Update(generic.CreateView):
    template_name = "estadios/update.html"
    model = Estadio
    form_class = UpdateEstadiosForm
    success_url = reverse_lazy('estadios:list')


class Delete(generic.DeleteView):
    template_name = "estadios/delete.html"
    model = Estadio
    success_url = reverse_lazy('estadios:list')

NFL/templates/estadios/create.html
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Agregar estadio</button>
        <a href="{% url 'estadios:list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>

NFL/templates/estadios/delete.html
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Deseas eliminar: {{ object }}?
        <button type="submit" class="btn btn-primary">Eliminar estadios</button>
        <a href="{% url 'estadios:list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>

NFL/templates/estadios/detail.html
<h1>Nombre estadio: {{ object.nombre }}</h1>
<h1>Ciuada del estadio: {{ object.ciudad }}</h1>

NFL/templates/estadios/list.html
<a href="{% url 'estadios:create' %}">Agregar ciudad</a>
<br>
<table>
    <thead>
      <th>ID</th>
      <th>NOMBRE</th>
      <th>CIUDAD</th>
      <th></th>
      <th>ACTIONS</th>
      <th></th>
    </thead>
    <tbody>
      {% for x in estadios %}
        <tr>
          <td>{{ x.id }}</td>
          <td>{{ x.name }}</td>
          <td><a href="{% url 'cities:city_detail' city.id %}" class="btn btn-info">Details</a></td>
          <td><a href="{% url 'cities:city_update' city.id %}" class="btn btn-warning">Update</a></td>
          <td><a href="{% url 'cities:city_delete' city.id %}" class="btn btn-primary">Delete</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

NFL/templates/estadios/update.html
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Actualizar estadio</button>
        <a href="{% url 'estadios:list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>